import React, { useState } from 'react';
import Head from 'next/head'
import BaseHeader from '../components/BaseHeader';
import BaseTextInputWithButton from '../components/BaseTextInputWithButton';
import TodoList from "../components/TodoList";
import styles from '../styles/Home.module.css'

export default function Home() {

    const onAddTodo = (text) => {

        const newList = {
            id: Date.now(),
            text: text
        }
        setTodos([...todos, newList])
    }
    const [todos, setTodos] = useState([]);

    const onRemoveTodo = (id) => {
        console.log('onRemoveTodo')
        const filteredTodo = todos.filter((todo) => {

            return todo.id !== id
        })
        setTodos(filteredTodo)
    }

    return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <BaseHeader></BaseHeader>

        <main className={styles.main}>
            <h1 className={styles.title}>
                To do list
            </h1>

            <div>
                <form className={styles.form} action="">
                    <BaseTextInputWithButton
                        inputId='todo-input'
                        inputName='todo-input'
                        placeholder='Organize desktop...'
                        buttonText='Add'
                        onClick={onAddTodo}
                    />
                </form>
            </div>

            <div>
                <TodoList
                    items={todos}
                    onRemoveTodo={onRemoveTodo}
                />
            </div>
        </main>
    </>
  )
}
